change ratingsAverage min value
AsliSema/byte-and-bite pull request #43
Opened 2023-07-17 16:04 UTC by AsliSema

change ratingsAverage min value in the dish model

2023-07-17 16:17 UTC, Khaled6120 requested changes

2023-07-17 16:17 UTC, Khaled6120 commented on src/models/dish.ts
> +        min: [0, 'Rating must be equal or greater than 1'],
can you plz update the msg as well, sorry for that again 
`  min: [0, 'Rating must be equal or greater than 0'], `

2023-07-17 16:21 UTC, Rsmk-code approved these changes

2023-07-18 09:59 UTC, Khaled6120 approved these changes
Thank you Aslı

2023-07-18 10:02 UTC, merged